services:
  kantin-recommender:
    image: orderherekiosk/fnb-ml-container:v2
    container_name: OH-kantin_recommender-v2
    
    ports:
      - "8067:8000"

    environment:
      - PYTHONUNBUFFERED=1