services:
  kantin-recommender:
    image: orderherekiosk/fnb-ml-container:v5
    container_name: OH-kantin_recommender-v5
    
    ports:
      - "8067:8000"

    environment:
      - PYTHONUNBUFFERED=1